### ISSUE TITLE
Routing implementation

### ISSUE THREAD

**Issue by stephanevieira75** [TwakeApp/Twake#425]
# To do:

## Part 1
- [x] Add react-router-dom package
- [x] Add login, error, setup and client routes
- [x] Update project architecture based on the new routes

## Part 2
- [x] Client router params `web.twake.app/client/workspace-id/c/channel-id`
- [x] Generate shortened id for url
- [ ] Update views while changing routes
